// npm run dev:keys -- [--llm-provider stub|openai-compatible] [--llm-base-url URL] [--llm-model NAME] [--rotate]
// Writes .dev.vars (gitignored): a local RS256 key pair for the dev token issuer
// (DEV_ACCESS_JWKS, DEV_ACCESS_PRIVATE_JWK) and the dev server's LLM provider. Existing keys are kept
// unless --rotate is passed, so switching providers does not log you out.
// Tests are immune to this file: every Vitest workerd project pins every config key.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { parseArgs } from "node:util";
import { calculateJwkThumbprint, exportJWK, generateKeyPair } from "jose";

const repo = resolve(import.meta.dirname, "..");
const path = join(repo, ".dev.vars");
const { values } = parseArgs({
  options: {
    "llm-provider": { type: "string" },
    "llm-base-url": { type: "string" },
    "llm-model": { type: "string" },
    rotate: { type: "boolean", default: false },
  },
});

const provider = values["llm-provider"];
if (provider !== undefined && provider !== "stub" && provider !== "openai-compatible") {
  console.error("--llm-provider must be stub or openai-compatible (workers-ai needs a deployed Worker)");
  process.exit(1);
}

function parseDevVars(text: string): Map<string, string> {
  const out = new Map<string, string>();
  for (const line of text.split("\n")) {
    const m = /^([A-Z0-9_]+)=(.*)$/.exec(line.trim());
    if (!m) continue;
    let v = m[2] ?? "";
    if ((v.startsWith("'") && v.endsWith("'")) || (v.startsWith('"') && v.endsWith('"'))) v = v.slice(1, -1);
    out.set(m[1] as string, v);
  }
  return out;
}

const vars = existsSync(path) ? parseDevVars(readFileSync(path, "utf8")) : new Map<string, string>();
if (values.rotate || !vars.get("DEV_ACCESS_JWKS") || !vars.get("DEV_ACCESS_PRIVATE_JWK")) {
  const { publicKey, privateKey } = await generateKeyPair("RS256", { extractable: true });
  const pub = await exportJWK(publicKey);
  const kid = await calculateJwkThumbprint(pub);
  vars.set("DEV_ACCESS_JWKS", JSON.stringify({ keys: [{ ...pub, kid, alg: "RS256", use: "sig" }] }));
  vars.set("DEV_ACCESS_PRIVATE_JWK", JSON.stringify({ ...(await exportJWK(privateKey)), kid, alg: "RS256" }));
  console.log(`Generated a new dev RS256 key pair (kid ${kid}).`);
}
vars.set("LLM_PROVIDER", provider ?? vars.get("LLM_PROVIDER") ?? "stub");
if (values["llm-base-url"]) vars.set("LLM_BASE_URL", values["llm-base-url"]);
if (values["llm-model"]) vars.set("LLM_MODEL", values["llm-model"]);

const lines = ["# Generated by npm run dev:keys. Local only; never commit this file."];
for (const [k, v] of vars) lines.push(`${k}='${v}'`);
writeFileSync(path, `${lines.join("\n")}\n`, { mode: 0o600 });
console.log(`Wrote ${path} (LLM_PROVIDER=${vars.get("LLM_PROVIDER")}).`);
